#!/bin/sh
### BEGIN INIT INFO
# Provides:          stegmap
# Required-Start:    $syslog $local_fs stegd
# Required-Stop:     $syslog $local_fs stegd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mount mapped stegOS devices
### END INIT INFO

case "$1" in
  start)
    echo -n "Mounting StegOS devices: "
    /usr/bin/stegmap mount
    echo "done."
    ;;
  stop)
    echo -n "Unmounting StegOS devices: "
    /usr/bin/stegmap unmount
    echo "done."
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/stegmap {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
