#!/bin/sh
### BEGIN INIT INFO
# Provides:          stegmap
# Required-Start:    $syslog $local_fs stegd
# Required-Stop:     $syslog $local_fs stegd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mount mapped stegOS devices
### END INIT INFO

case "$1" in
  start)
    echo -n "Mounting stegOS devices: "
    # Wait for the stegd socket to be ready
    for i in 1 2 3 4 5; do
        if [ -S /run/stegos/stegos.sock ]; then
            break
        fi
        sleep 1
    done
    /usr/bin/stegmap mount
    echo "done."
    ;;
  stop)
    echo -n "Unmounting stegOS devices: "
    /usr/bin/stegmap unmount
    echo "done."
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/stegmap {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
